# Generated by Django 4.0.5 on 2023-01-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_profile_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Builder', 'Builder')], default='Buyer', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
