# Generated by Django 4.0.5 on 2023-01-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_profile_usertype_alter_profile_forgot_password_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': {('buyer', 'buyer'), ('seller', 'seller'), ('builder', 'builder')}},
        ),
    ]
