# Generated by Django 4.0.5 on 2023-02-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
