# Generated by Django 4.0.5 on 2023-03-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
