# Generated by Django 4.0.5 on 2023-04-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_buyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
