# Generated by Django 4.0.5 on 2023-04-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_delete_buyer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': {('builder', 'builder'), ('buyer', 'buyer'), ('supervisor', 'supervisor'), ('seller', 'seller')}},
        ),
    ]
