# Generated by Django 4.0.5 on 2023-03-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_image',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.property'),
            preserve_default=False,
        ),
    ]
