# Generated by Django 4.0.5 on 2023-03-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_property_image_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='dynamic_fileds',
            new_name='dynamic_fields',
        ),
    ]
