# Generated by Django 4.0.5 on 2023-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_property_image_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_image',
            name='image1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='property_image',
            name='image2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='property_image',
            name='image3',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='property_image',
            name='image4',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='property_image',
            name='image5',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
