# Generated by Django 4.0.5 on 2023-03-27 05:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_property_image_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_image',
            name='image1',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
