# Generated by Django 4.0.5 on 2023-03-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_property_image_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_image',
            name='image1',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
