# Generated by Django 4.0.5 on 2023-03-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_property_image1_remove_property_image_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_image',
            name='image2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property_image',
            name='image3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property_image',
            name='image4',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='property_image',
            name='image5',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='property_image',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
