# Generated by Django 4.0.5 on 2023-04-07 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_property_image_image2_property_image_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_image',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
