# Generated by Django 4.0.5 on 2023-04-13 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_property_image_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
