# Generated by Django 4.0.5 on 2023-04-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_delete_buyer'),
        ('dashboard', '0018_alter_property_user_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
        migrations.AlterField(
            model_name='property',
            name='user_seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.profile'),
        ),
    ]
