# Generated by Django 4.0.5 on 2023-04-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_property_user_alter_property_user_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_image',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_furnished_status',
            field=models.CharField(blank=True, choices=[('Full Furnished', 'Full Furnished'), ('No Furnished', 'No Furnished')], default='less than 5 years', max_length=50, null=True),
        ),
    ]
