# Generated by Django 4.0.5 on 2023-04-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_property_image_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_image',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
