# Generated by Django 4.0.5 on 2023-04-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_property_image_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
