# Generated by Django 4.0.5 on 2023-04-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_profile_options'),
        ('dashboard', '0022_property_property_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_furnished_status',
            field=models.CharField(blank=True, choices=[('Full Furnished', 'Full Furnished'), ('No Furnished', 'No Furnished')], default='No Furnished', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50)),
                ('property_address', models.CharField(max_length=200)),
                ('property_state', models.CharField(max_length=100)),
                ('property_city', models.CharField(max_length=100)),
                ('dynamic_fields', models.JSONField(default=None)),
                ('property_furnished_status', models.CharField(blank=True, choices=[('Full Furnished', 'Full Furnished'), ('No Furnished', 'No Furnished')], default='No Furnished', max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(default='', upload_to='images/')),
                ('image3', models.ImageField(default='', upload_to='images/')),
                ('image4', models.ImageField(default='', upload_to='images/')),
                ('image5', models.ImageField(default='', upload_to='images/')),
                ('booklet', models.FileField(default='', upload_to='booklet/')),
                ('slug', models.SlugField(unique=True)),
                ('builder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.profile')),
            ],
        ),
    ]
